### ISSUE TITLE
Unable to run this project

### ISSUE THREAD

**Issue by supportreq** [yogdaan/blockchain-certification#16]
Hi,

I tried installing this on Ubuntu 20.04, Amazon Linux, even docker, yet this is unable to deploy on any of the platform.. 

It returns error while running npm run contract-deploy

Please advice the configuration.

**Comment by supportreq** [comment]
@thakursaurabh1998 any suggestions?

**Comment by thakursaurabh1998** [comment]
> @thakursaurabh1998 any suggestions? 

Can you share the errors you are getting?

**Comment by supportreq** [comment]
@thakursaurabh1998 

My server settings are as under:
- Ubuntu 20.04
- NodeJS 15.x
- MongoDB

Steps for compiling:
- updated the mongodb details in .env file
- npm run ganache
- npm run contract-deploy
$ npm run contract-deploy

> certification-server@0.0.2 contract-deploy
> truffle.cmd migrate --reset || truffle migrate --reset
```
sh: 1: truffle.cmd: not found
Error: Cannot find module 'babel-register'
Require stack:
- /home/ubuntu/blockchain/blockchain-certification/truffle.js
- /usr/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/ubuntu/blockchain/blockchain-certification/truffle.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at Object.require (node:internal/modules/cjs/helpers:92:18)
    at Function.load (/usr/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/usr/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:199:1)
    at Command.run (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.586806 (/usr/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:51:1)
    at __webpack_require__ (/usr/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:18:1)
    at __webpack_require__.x (/usr/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:36:1)
    at Function.__webpack_require__.x (/usr/lib/node_modules/truffle/build/webpack:/webpack/runtime/startup chunk dependencies:32:1)
    at /usr/lib/node_modules/truffle/build/webpack:/webpack/startup:3:1
    at Object.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:629:12)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
Truffle v5.2.4 (core: 5.2.4)
Node v15.12.0
npm ERR! code 1
npm ERR! path /home/ubuntu/blockchain/blockchain-certification
npm ERR! command failed
npm ERR! command sh -c truffle.cmd migrate --reset || truffle migrate --reset

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-19T12_11_22_638Z-debug.log
```

**Comment by supportreq** [comment]
did $npm install but getting following:
```
$ npm install
The authenticity of host 'github.com (13.234.176.102)' can't be established.e-js Completed in 35319ms
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? [                  ] \ reify:bignumber.js: timing reifyNode:node_modules[                  ] - reify:bignumber.js: timing reifyNode:node_modules/core-js Completed in 35319ms
npm ERR! code 128
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/ubuntu/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 128
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command git ls-remote ssh://git@github.com/gulpjs/gulp.git
npm ERR! npm ERR! Host key verification failed.
npm ERR! npm ERR! fatal: Could not read from remote repository.
npm ERR! npm ERR! 
npm ERR! npm ERR! Please make sure you have the correct access rights
npm ERR! npm ERR! and the repository exists.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/ubuntu/.npm/_logs/2021-03-19T12_10_53_688Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-19T12_10_55_642Z-debug.log
```

**Comment by supportreq** [comment]
@thakursaurabh1998 any luck?

**Comment by supportreq** [comment]
@thakursaurabh1998 can you help please?

**Comment by justaluckyguy** [comment]
I have the sam problem,It is difficult to fix

**Comment by MrAnayDongre** [comment]
GitHub updated their RSA SSH host key.  [LINK](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/)
